language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITARM=/opt/devkitpro/devkitARM
    
cache:
  directories:
    - "$HOME/.local"
    - "$DEVKITPRO"

before_install:
  - curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
  - curl -L https://github.com/Steveice10/bannertool/releases/download/1.1.0/bannertool.zip -o bannertool.zip
  - sudo apt-get install -y p7zip-full

install:
  - sudo dpkg -i pacman.deb
  - sudo dkp-pacman -Sy
  - sudo dkp-pacman -S devkitARM general-tools 3dstools picasso 3ds-curl 3ds-libarchive 3ds-liblzma 3ds-mbedtls 3ds-bzip2 3ds-zlib --noconfirm
  - 
  - sudo 7z e bannertool.zip linux-x86_64/bannertool
  - export PATH=$PATH:$(pwd)
  - ls -a
  - pwd
  -
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

script:
  # - sudo 7z x libctru.7z -o/opt/devkitpro/
  # - curl -L https://github.com/Steveice10/bannertool/releases/download/1.1.0/bannertool.zip -o bannertool.zip
  # - sudo 7z e bannertool.zip linux-x86_64/bannertool -o/opt/devkitPro/tools/bin/
  # - rm bannertool.zip
  # - curl -L https://github.com/profi200/Project_CTR/releases/download/0.15/makerom_015_ctrtool.zip -o makerom_015_ctrtool.zip
  # - sudo 7z e makerom_015_ctrtool.zip Linux_x86_64/makerom -o/opt/devkitpro/tools/bin/
  # - rm makerom_015_ctrtool.zip
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  - make
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp

# after_success:
#   - curl -o send.sh https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
#   - chmod +x send.sh
#   - ./send.sh success $WEBHOOK_URL

# after_failure:
#   - curl -o send.sh https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
#   - chmod +x send.sh
#   - ./send.sh failure $WEBHOOK_URL

before_deploy:
  - git config --local user.name "TWLBot"
  - git clone https://$GITHUB_TOKEN@github.com/TWLBot/Builds.git
  - cd Builds/
  - cp ../TWiLightMenu.7z TWiLightMenu.7z
  - git stage .
  - git commit -m "TWiLightMenu Updater | $COMMIT_TAG"
  - git push origin master
  - export CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')
  - git tag v$CURRENT_DATE

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - TWiLight_Menu++_Updater.3dsx
    - TWiLight_Menu++_Updater.cia
  skip_cleanup: true
  repo: TWLBot/Builds
  prerelease: true
  name: TWiLightMenu Updater | $COMMIT_TAG
  body: $COMMIT_MESSAGE
